---
# Here we use  _galaxy_ansible_com_galaxy to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_galaxy_ansible_com_galaxy']['spec'] }}"

container_auth_public_key_name: 'container_auth_public_key.pem'
container_auth_private_key_name: 'container_auth_private_key.pem'

# Keycloack SSO settings
keycloak_admin_role: hubadmin
keycloak_port: 443
keycloak_protocol: https

sso_secret_data_available: false
social_auth_keycloak_key_available: false
social_auth_keycloak_secret_available: false
social_auth_keycloak_public_key_available: false
keycloak_host_available: false
keycloak_protocol_available: false
keycloak_port_available: false
keycloak_realm_available: false

gunicorn_timeout: 90
gunicorn_api_workers: 2
