---

- name: Set apiVersion and kind variables
  set_fact:
    api_version: '{{ hostvars["localhost"]["inventory_file"].split("/")[4:6] | join("/")  }}'
    kind: '{{ hostvars["localhost"]["inventory_file"].split("/")[6]  }}'

- name: Update migrantDatabaseConfigurationSecret status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      migrantDatabaseConfigurationSecret: "{{ postgres_migrated_from_secret }}"
  when:
    - postgres_migrated_from_secret is defined
    - postgres_migrated_from_secret | length

# This signifies that the PostgreSQL upgrade is complete and the version it was upgraded to
- name: Update upgradedPostgresVersion status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      upgradedPostgresVersion: "{{ upgraded_postgres_version | string }}"
  when:
    - upgraded_postgres_version is defined

- name: Get the resource pod information.
  k8s_info:
    kind: Pod
    api_version: v1
    namespace: '{{ ansible_operator_meta.namespace }}'
    label_selectors:
      - "app.kubernetes.io/instance=nginx-{{ ansible_operator_meta.name }}"
  register: galaxy_pods
  until: "galaxy_pods['resources'][0]['status']['phase'] == 'Running'"
  delay: 5
  retries: 100
  when:
    - ingress_type | lower != 'route'

- name: Manage deployed version
  ansible.builtin.include_tasks: version.yml

- name: Remove resource manager deployment
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: "{{ ansible_operator_meta.name }}-resource-manager"
    namespace: "{{ ansible_operator_meta.namespace }}"
    state: absent
  when: installed_plugins.core is version('3.16.0', '>=')

- name: Update admin password status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      adminPasswordSecret: "{{ admin_password_secret_obj['resources'][0]['metadata']['name'] }}"

- name: Update database configuration status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      databaseConfigurationSecret: "{{ pg_config['resources'][0]['metadata']['name'] }}"

- name: Update storage type status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      storageType: "{{ storage_type | capitalize }}"

- name: Update file storage pvc name status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      storagePersistentVolumeClaim: "{{ ansible_operator_meta.name }}-file-storage"
  when: is_file_storage

- name: Update object storage secret name status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      storageSecret: "{{ object_storage_secret }}"
  when: not is_file_storage

- name: Update DB fields encryption secret name status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      dbFieldsEncryptionSecret: "{{ db_fields_encryption_secret }}"
  when: db_fields_encryption_secret is defined

- name: Update galaxy signing secret name status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      signingSecret: "{{ signing_secret }}"
  when: signing_secret is defined

- name: Update container token secret name status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      containerTokenSecret: "{{ container_token_secret }}"
  when: container_token_secret is defined

- name: Update upgradedFrom status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      upgradedFrom: "{{ upgraded_from }}"
  when: upgraded_from is defined

- name: Update image status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      deployedImage: "{{ _custom_image | default(lookup('env', 'RELATED_IMAGE_GALAXY')) | default(_default_image) }}"

- block:
    - name: Retrieve route URL
      k8s_info:
        kind: Route
        api_version: "route.openshift.io/v1"
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ ansible_operator_meta.name }}'
      register: route_url

    - name: Update URL status
      operator_sdk.util.k8s_status:
        api_version: '{{ api_version }}'
        kind: "{{ kind }}"
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          webURL: "https://{{ route_url['resources'][0]['status']['ingress'][0]['host'] }}"

  when: ingress_type | lower == 'route'

- k8s_status:
    api_version: "{{ api_version }}"
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    conditions:
      - type: "{{ deployment_type|capitalize }}-Operator-Finished-Execution"
        message: All tasks ran successfully
        reason: OperatorFinishedExecution
        status: "True"
        lastTransitionTime: "{{ lookup('pipe', 'date --iso-8601=seconds') }}"
