---
- name: Load Route TLS certificate
  ansible.builtin.include_tasks: load_route_tls_secret.yml
  when:
    - ingress_type | lower == 'route'
    - route_tls_secret != ''

- name: Galaxy Route
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.ingress.yaml.j2') }}"
  with_items:
    - galaxy
  when:
    - ingress_type is defined
    - ('route' == ingress_type|lower) or ('ingress' == ingress_type|lower)

- name: Remove deprecated {{ deployment_type }} Routes when present for {{ ansible_operator_meta.name }} from {{ ansible_operator_meta.namespace }} namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Route
    namespace: "{{ ansible_operator_meta.namespace }}"
    name: "{{ item }}"
  loop:
    - "{{ ansible_operator_meta.name }}-ansible-pulp-ansible-galaxy"
    - "{{ ansible_operator_meta.name }}-api-v3"
    - "{{ ansible_operator_meta.name }}-auth"
    - "{{ ansible_operator_meta.name }}-container-extensions-v2"
    - "{{ ansible_operator_meta.name }}-container-pulp-container"
    - "{{ ansible_operator_meta.name }}-container-token"
    - "{{ ansible_operator_meta.name }}-container-v2"
    - "{{ ansible_operator_meta.name }}-content"
    - "{{ ansible_operator_meta.name }}-galaxy-api"
    - "{{ ansible_operator_meta.name }}-galaxy-ui"
    - "{{ ansible_operator_meta.name }}-galaxy-ui2"
  when: ingress_type | lower == 'route'

- k8s_status:
    api_version: "{{ api_version }}"
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    conditions:
      - type: "{{ deployment_type|capitalize }}-Routes-Ready"
        message: Checking routes
        reason: CheckingRoutes
        status: "True"
        lastTransitionTime: "{{ lookup('pipe', 'date --iso-8601=seconds') }}"
