---
- name: Set apiVersion and kind variables
  set_fact:
    api_version: '{{ hostvars["localhost"]["inventory_file"].split("/")[4:6] | join("/")  }}'
    kind: '{{ hostvars["localhost"]["inventory_file"].split("/")[6]  }}'

- name: Get object definition from pvc
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-backup-manager"
    command: >-
      bash -c "cat '{{ backup_dir }}/cr_object'"
  register: cr_object

- name: Set custom resource spec variable from backup
  set_fact:
    cr_spec: "{{ cr_object.stdout }}"
    cr_spec_strip: "{ "
    admin_str: "admin_password_secret: {{ admin_password_name }}"
    storage_str: "object_storage_{{ storage_type | lower }}_secret: {{ storage_secret }}"
    storage_key: "object_storage_{{ storage_type | lower }}_secret"
    container_token_str: "container_token_secret: {{ container_token_secret }}"
    db_fields_str: "db_fields_encryption_secret: {{ db_fields_encryption_secret }}"
    signing_str: "signing_secret: {{ signing_secret }}"
    db_str: "postgres_configuration_secret: {{ db_secret_name }}"
    sso_str: "sso_secret: {{ sso_secret }}"

# TODO: Convert all of these tasks to use the combine filter
- name: Remove postgres_configuration_secret from spec
  set_fact:
    cr_object: "{{ cr_object | combine({'postgres_configuration_secret': db_str}, recursive=True) }}"
  when:
    - database_type is defined
    - database_type == 'managed'

- name: Strip end characters from spec
  set_fact:
    cr_spec_strip: "{{ cr_object.stdout[:-2] }}"
  when:
    - cr_object.stdout | length > 1

- name: Set custom resource spec admin from backup
  set_fact:
    cr_spec_strip: "{{ cr_spec_strip + ', ' + admin_str }}"
  when: not 'admin_password_secret' in cr_object.stdout

- name: Set custom resource spec storage from backup
  set_fact:
    cr_spec_strip: "{{ cr_spec_strip + ', ' + storage_str }}"
  when:
    - not storage_key in cr_object.stdout
    - storage_type | lower != 'file'

- name: Set custom resource spec container token from backup
  set_fact:
    cr_spec_strip: "{{ cr_spec_strip + ', ' + container_token_str }}"
  when: not 'container_token_secret' in cr_object.stdout

- name: Set custom resource spec db encryption from backup
  set_fact:
    cr_spec_strip: "{{ cr_spec_strip + ', ' + db_fields_str }}"
  when: not 'db_fields_encryption_secret' in cr_object.stdout

- name: Set custom resource spec galaxy signing from backup
  set_fact:
    cr_spec_strip: "{{ cr_spec_strip + ', ' + signing_str }}"
  when:
    - not 'signing_secret' in cr_object.stdout
    - signing_secret != ''

- name: Set custom resource spec SSO from backup
  set_fact:
    cr_spec_strip: "{{ cr_spec_strip + ', ' + sso_str }}"
  when:
    - not 'sso_secret' in cr_object.stdout
    - sso_secret != ''

- name: Set custom resource spec from backup
  set_fact:
    cr_spec: "{{ cr_spec_strip + '}\n' }}"

- name: Deploy object
  k8s:
    state: present
    definition: "{{ lookup('template', 'galaxy_object.yaml.j2') }}"
    wait: true

- name: Remove ownerReferences to prevent garbage collection of new CR
  k8s:
    definition:
      apiVersion: '{{ api_version }}'
      kind: Galaxy
      metadata:
        name: '{{ deployment_name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
