---
- name: Delete any existing management pod
  k8s:
    name: "{{ ansible_operator_meta.name }}-db-management"
    kind: Pod
    api_version: v1
    namespace: "{{ backup_pvc_namespace }}"
    state: absent
    force: true
