---
- name: Delete any existing management pod
  k8s:
    name: "{{ ansible_operator_meta.name }}-backup-manager"
    kind: Pod
    namespace: "{{ backup_pvc_namespace }}"
    state: absent
    force: true
