---
deployment_type: galaxy

worker:
  replicas: 2
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi

# Here we use  _pulp_pulpproject_org_pulp to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_pulp_pulpproject_org_pulp']['spec'] }}"
