---
apiVersion: galaxy.ansible.com/v1beta1
kind: Galaxy
metadata:
  name: galaxy
spec:
  ingress_type: Route

  image_pull_policy: Always
  no_log: false

  # signing configuration
  signing_secret: "signing-galaxy"
  signing_scripts_configmap: "signing-scripts"

  # content storage
  storage_type: File
  file_storage_access_mode: "ReadWriteMany"
  file_storage_size: "10Gi"
  file_storage_storage_class: nfs-local-rwx

  pulp_settings:
    api_root: "/api/galaxy/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    telemetry: false

  postgres_extra_settings:
    - setting: max_connections
      value: "999"
    - setting: ssl_ciphers
      value: "HIGH:!aNULL:!MD5"

  database:
    # postgres_storage_class: standard

    # requires galaxy-postgres-configuration secret to be pre-created
    postgres_configuration_secret: galaxy-postgres-configuration
  postgres_resource_requirements:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 800m
      memory: 1Gi
  postgres_storage_requirements:
    requests:
      storage: 20Gi
    limits:
      storage: 100Gi
