apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "storage-type-validation"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["galaxy.ansible.com"]
      apiVersions: ["*"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["galaxies"]
  validations:
  - expression: "has(object.spec.storage_type)"
    message: "storage_type should not be empty"
    reason: Invalid
  - expression: "!(object.spec.storage_type in ['File', 'file'] && !has(object.spec.file_storage_storage_class))"
    message: "please specify a rwx file_storage_storage_class"
    reason: Invalid
  - expression: "!(object.spec.storage_type in ['S3', 's3'] && !has(object.spec.object_storage_s3_secret))"
    message: "object_storage_s3_secret should not be empty"
    reason: Invalid
  - expression: "!(object.spec.storage_type in ['Azure', 'azure'] && !has(object.spec.object_storage_azure_secret))"
    message: "object_storage_azure_secret should not be empty"
    reason: Invalid
