---
- name: pulp-file-storage
  block:
    - name: "Creating {{ deployment_type|capitalize }}-api PVC resource"
      k8s_status:
        api_version: "{{ api_version }}"
        kind: "{{ kind }}"
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        conditions:
          - type: "{{ deployment_type|capitalize }}-API-Ready"
            message: "Creating {{ deployment_type|capitalize }}-api PVC resource"
            reason: CreatingPVC
            status: "False"
            lastTransitionTime: "{{ lookup('pipe', 'date --iso-8601=seconds') }}"

    - name: pulp-file-storage persistent volume claim
      k8s:
        state: "{{ deployment_state }}"
        definition: "{{ lookup('template', 'templates/' + item + '.pvc.yaml.j2') | from_yaml }}"
      with_items:
        - pulp-file-storage

    - name: "Removing ownerReferences from {{ ansible_operator_meta.name}}-file-storage PVC"
      k8s_status:
        api_version: "{{ api_version }}"
        kind: "{{ kind }}"
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        conditions:
          - type: "{{ deployment_type|capitalize }}-API-Ready"
            message: "Removing ownerReferences from {{ ansible_operator_meta.name}}-file-storage PVC"
            reason: RemovingPVCOwnerReferences
            status: "False"
            lastTransitionTime: "{{ lookup('pipe', 'date --iso-8601=seconds') }}"

    - name: Remove ownerReferences from pulp-file-storage pvc to avoid garbage collection
      k8s:
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: '{{ ansible_operator_meta.name }}-file-storage'
            namespace: '{{ ansible_operator_meta.namespace }}'
            ownerReferences: null

  when: is_file_storage
