---

- name: Create directory for backup content files
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-backup-manager"
    command: >-
      mkdir -p {{ _backup_dir }}/pulp/

- name: Set file copy command
  set_fact:
    copy_cmd: >-
      cp -fr /var/lib/pulp/. {{ _backup_dir }}/pulp

- name: Write content files to backup on PVC
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-backup-manager"
    command: >-
      bash -c "{{ copy_cmd }}"
  register: file_copy
