---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: galaxy-operator-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - rbac.authorization.k8s.io
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - roles
      - rolebindings
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
      - networking.k8s.io
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments/scale
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - galaxy-operator-sa
    resources:
      - serviceaccounts
    verbs:
      - patch
      - get
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - create
      - patch
      - update
      - watch

  ##
  ## Rules for galaxy.ansible.com/v1beta1, Kind: Galaxy
  ##
  - apiGroups:
      - galaxy.ansible.com
    resources:
      - galaxies
      - galaxies/status
      - galaxies/finalizers
      - galaxybackups
      - galaxybackups/status
      - galaxybackups/finalizers
      - galaxyrestores
      - galaxyrestores/status
      - galaxyrestores/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
