---
content:
  replicas: 2
  log_level: INFO
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 4Gi

ingress_type: none

# Here we use  _pulp_pulpproject_org_pulp to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_pulp_pulpproject_org_pulp']['spec'] }}"

gunicorn_timeout: 90
gunicorn_content_workers: 2
