apiVersion: galaxy.ansible.com/v1beta1
kind: Galaxy
metadata:
  name: galaxy-demo
spec:
  ingress_type: Ingress
  image: quay.io/ansible/galaxy-ng
  image_version: latest
  image_web: quay.io/ansible/galaxy-ui
  image_web_version: latest
  admin_password_secret: "example-galaxy-admin-password"
  container_token_secret: "container-auth"
  storage_type: File
  # k3s local-path requires this
  file_storage_access_mode: "ReadWriteMany"
  # We have a little over 10GB free on GHA VMs/instances
  file_storage_size: "10Gi"
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
