apiVersion: galaxy.ansible.com/v1beta1
kind: Galaxy
metadata:
  name: example-galaxy
spec:
  image_version: nightly
  image_web_version: nightly
  admin_password_secret: "example-galaxy-admin-password"
  db_fields_encryption_secret: "custom-db-fields-encryption"
  storage_type: File
  ingress_type: nodeport
  file_storage_access_mode: "ReadWriteOnce"
  file_storage_size: "10Gi"
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
