apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: pulp-s3
spec:
  ingress_type: Ingress
  admin_password_secret: "example-pulp-admin-password"
  settings:
    debug: "True"
  storage_type: S3
  object_storage_s3_secret: example-pulp-object-storage
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
