# Adds namespace to all resources.
namespace: osdk-test

namePrefix: osdk-

# Labels to add to all resources and selectors.
#- includeSelectors: true
#  pairs:
#    someName: someValue

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: osdk-test
    target:
      kind: RoleBinding
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: osdk-test
    target:
      kind: ClusterRoleBinding
  - patch: |-
      - op: replace
        path: /subjects/0/name
        value: osdk-sa
    target:
      kind: RoleBinding
  - patch: |-
      - op: replace
        path: /subjects/0/name
        value: osdk-sa
    target:
      kind: ClusterRoleBinding

patchesStrategicMerge:
- manager_image.yaml
- debug_logs_patch.yaml
- ../default/manager_auth_proxy_patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac
- ../manager
images:
- name: testing
  newName: testing-operator
