---
resource_manager:
  # Waiting on this to be implemented:
  # https://pulp.plan.io/issues/3707
  replicas: 1
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

# Here we use  _pulp_pulpproject_org_pulp to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_pulp_pulpproject_org_pulp']['spec'] }}"
