FROM quay.io/ansible/galaxy-ng:latest

USER root

# Install python nginx package
RUN pip3 install python-nginx

COPY route_paths.py /usr/bin/route_paths.py
COPY readyz.py /usr/bin/readyz.py
COPY wait_on_postgres.py /usr/bin/wait_on_postgres.py

# Pre-create things we need to access
RUN for file in \
      /usr/bin/route_paths.py \
      /usr/bin/wait_on_postgres.py \
      /usr/bin/readyz.py ; \
    do touch $file ; chmod g+rw+x $file ; chgrp root $file ; done

USER 1000
