---
# Host to create the root with.
# If not specific will default to <instance-name>-<namespace>-<routerCanonicalHostname>
#
route_host: ''

hostname: '{{ deployment_type }}.example.com'


# https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
nginx_client_max_body_size: 10m

nginx_proxy_read_timeout: 120s
nginx_proxy_connect_timeout: 120s
nginx_proxy_send_timeout: 120s

haproxy_timeout: 180s

# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
# https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/
# Add annotations to the ingress. Specify as literal block. E.g.:
# ingress_annotations: |
#   kubernetes.io/ingress.class: nginx
#   nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
ingress_annotations: |
  nginx.ingress.kubernetes.io/proxy-body-size: {{ nginx_client_max_body_size }}
  nginx.org/client-max-body-size: {{ nginx_client_max_body_size }}
  nginx.ingress.kubernetes.io/proxy-read-timeout: {{ nginx_proxy_read_timeout }}
  nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ nginx_proxy_connect_timeout }}
  nginx.ingress.kubernetes.io/proxy-send-timeout: {{ nginx_proxy_send_timeout }}
  haproxy.router.openshift.io/timeout: {{ haproxy_timeout }}
