---

- k8s_status:
    api_version: "{{ api_version }}"
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    conditions:
      - type: "{{ deployment_type|capitalize }}-API-Ready"
        message: "Creating {{ ansible_operator_meta.name }}-server Secret resource"
        reason: CreatingServerSecret
        status: "False"
        lastTransitionTime: "{{ lookup('pipe', 'date --iso-8601=seconds') }}"

- name: galaxy-server secret
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/galaxy-server.secret.yaml.j2') | from_yaml }}"
  register: galaxy_server_secret
  no_log: "{{ no_log }}"
