---
ingress_type: none

# Here we use  _galaxy_ansible_com_galaxy to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_galaxy_ansible_com_galaxy']['spec'] }}"

gunicorn_timeout: 90
gunicorn_content_workers: 2
