- set_fact:
    object_storage_secret: "{{ object_storage_s3_secret }}"
  when:
    - object_storage_s3_secret is defined

- set_fact:
    object_storage_secret: "{{ object_storage_azure_secret }}"
  when:
    - object_storage_azure_secret is defined

- include_tasks:
    file: s3-storage-configuration.yml
  when:
    - not is_file_storage
    - object_storage_s3_secret is defined
    - object_storage_s3_secret | length

- include_tasks:
    file: azure-storage-configuration.yml
  when:
    - not is_file_storage
    - object_storage_azure_secret is defined
    - object_storage_azure_secret | length

- set_fact:
    is_file_storage: false
  when:
    - object_storage_secret is defined
