---
- name: Set default galaxy-api image
  set_fact:
    _default_image: "{{ _image }}:{{ _image_version }}"

- name: Set user provided galaxy-api image
  set_fact:
    _custom_image: "{{ image }}:{{ image_version }}"
  when:
    - image is defined and image != ''
    - image_version is defined and image_version != ''

- name: Set galaxy-api image URL
  set_fact:
    _image: "{{ _custom_image | default(lookup('env', 'RELATED_IMAGE_GALAXY')) | default(_default_image, true) }}"

- name: Set default galaxy-web image
  set_fact:
    _default_image_web: "{{ _image_web }}:{{ _image_web_version }}"

- name: Set user provided galaxy-web image
  set_fact:
    _custom_image_web: "{{ image_web }}:{{ image_web_version }}"
  when:
    - image_web is defined and image_web != ''
    - image_web_version is defined and image_web_version != ''

- name: Set galaxy-web image URL
  set_fact:
    _image_web: "{{ _custom_image_web | default(lookup('env', 'RELATED_IMAGE_GALAXY_WEB')) | default(_default_image_web, true) }}"
