---
postgres_version: 13
_postgres_image: postgres

postgres_storage_requirements:
  requests:
    storage: 8Gi
postgres_resource_requirements: {}

postgres_data_path: '/var/lib/postgresql/data/pgdata'

postgres_initdb_args: '--auth-host=scram-sha-256'
postgres_host_auth_method: 'scram-sha-256'

# Add a nodeSelector for the Postgres pods.
# It must match a node's labels for the pod to be scheduled on that node.
# Specify as literal block. E.g.:
# postgres_selector: |
#   disktype: ssd
#   kubernetes.io/arch: amd64
#   kubernetes.io/os: linux
postgres_selector: ''

# Specify whether or not to keep the old PVC after PostgreSQL upgrades
postgres_keep_pvc_after_upgrade: true

# Add node tolerations for the Postgres pods.
# Specify as literal block. E.g.:
# postgres_tolerations: |
#   - key: "dedicated"
#     operator: "Equal"
#     value: "Galaxy"
#     effect: "NoSchedule"
postgres_tolerations: ''

# Define postgres configuration arguments to use
postgres_extra_args: ''

custom_resource_key: '_galaxy_ansible_com_galaxy'
database_status_present: false

# Here we use  _galaxy_ansible_com_galaxy to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_galaxy_ansible_com_galaxy']['spec'] }}"
