---

- name: Check for presence of Deployment
  k8s_info:
    api_version: v1
    kind: Deployment
    name: "{{ deployment_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: scale_deployment

- name: Scale down Deployment for migration
  k8s_scale:
    api_version: v1
    kind: Deployment
    name: "{{ deployment_name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    replicas: 0
  when: scale_deployment['resources'] | length
