# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/galaxy-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replacements:
  - source:
      kind: Deployment
      name: galaxy-operator-controller-manager
      fieldPath: spec.template.spec.containers.1.image
    targets:
      - select:
          kind: ClusterServiceVersion
        fieldPaths:
          - metadata.annotations.containerImage
        options:
          create: true
