---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: galaxybackups.galaxy.ansible.com
spec:
  group: galaxy.ansible.com
  names:
    kind: GalaxyBackup
    listKind: GalaxyBackupList
    plural: galaxybackups
    singular: galaxybackup
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          description: Schema validation for the GalaxyBackup CRD
          properties:
            spec:
              type: object
              properties:
                deployment_name:
                  description: Name of the deployment to be backed up
                  type: string
                backup_pvc:
                  description: Name of the PVC to be used for storing the backup
                  type: string
                backup_pvc_namespace:
                  description: Namespace PVC is in (Deprecated)
                  type: string
                backup_storage_requirements:
                  description: Storage requirements for the backup
                  type: string
                backup_resource_requirements:
                  description: Resource requirements for the management pod used to create a backup
                  properties:
                    requests:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                    limits:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                  type: object
                backup_storage_class:
                  description: Storage class to use when creating PVC for backup
                  type: string
                postgres_label_selector:
                  description: Label selector used to identify postgres pod for executing migration
                  type: string
                no_log:
                  default: true
                  description: Configure no_log (hides sensitive information in operator/task logs)
                  type: boolean
              required:
                - deployment_name
            status:
              properties:
                deploymentName:
                  description: Name of the deployment backed up
                  type: string
                backupClaim:
                  description: The PVC name used for the backup
                  type: string
                backupNamespace:
                  description: The namespace used for the backup claim
                  type: string
                backupDirectory:
                  description: The directory data is backed up to on the PVC
                  type: string
                deploymentStorageType:
                  description: The deployment storage type
                  type: string
                adminPasswordSecret:
                  description: Administrator password secret used by the deployed instance
                  type: string
                databaseConfigurationSecret:
                  description: Database configuration secret used by the deployed instance
                  type: string
                storageSecret:
                  description: Objectstorage configuration secret used by the deployed instance
                  type: string
                dbFieldsEncryptionSecret:
                  description: DB fields encryption configuration secret used by deployed instance
                  type: string
                containerTokenSecret:
                  description: Container token configuration secret used by the deployed instance
                  type: string
                conditions:
                  description: The resulting conditions when a Service Telemetry is instantiated
                  items:
                    properties:
                      status:
                        type: string
                      type:
                        type: string
                      reason:
                        type: string
                      lastTransitionTime:
                        type: string
                    type: object
                  type: array
              type: object
