---

name: Build Operator Image

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push main image
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into registry quay.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Store Image @ghcr
        run: |
          IMG=ghcr.io/${{ github.repository_owner }}/galaxy-operator:${{ github.sha }} make docker-buildx

      - name: Publish Image to quay.io/ansible/galaxy-operator:main
        run: |
          docker buildx imagetools create ghcr.io/${{ github.repository_owner }}/galaxy-operator:${{ github.sha }} --tag quay.io/ansible/galaxy-operator:main
