name: Galaxy-Operator PR
on:
  pull_request:
env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
jobs:
  galaxy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - STORAGE: filesystem
            IMAGE: minimal
          - STORAGE: filesystem
            IMAGE: s6
          - STORAGE: azure
            IMAGE: minimal
          - STORAGE: s3
            IMAGE: minimal
    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"

      - uses: actions/checkout@v3
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          # Could be used to checkout the PR head repo when public
          # repository: ${{ steps.head_repo_name.outputs.repo }}
          # ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install httpie
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          echo "IMG=quay.io/ansible/galaxy-operator:main" >> $GITHUB_ENV
          echo "CI_TEST=true" >> $GITHUB_ENV
          echo "CI_TEST_STORAGE=${{ matrix.STORAGE }}" >> $GITHUB_ENV
          echo "CI_TEST_IMAGE=${{ matrix.IMAGE }}" >> $GITHUB_ENV
          echo "API_ROOT=/api/galaxy/pulp/" >> $GITHUB_ENV
        shell: bash

      - name: Start minikube
        run: |
          minikube start --memory=max --cpus=max --vm-driver=docker --extra-config=apiserver.service-node-port-range=80-32000 --kubernetes-version=v1.28.3
          minikube addons enable metrics-server
        # now you can run kubectl to see the pods in the cluster

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: Setup a minikube docker env
        run: minikube -p minikube docker-env | grep "export" | sed 's/export //' | sed 's/"//g' >> $GITHUB_ENV

      - name: Uninstalling GHA kustomize
        run: |
          # hack for uninstalling kustomize from GHA
          mv /usr/local/bin/kustomize /usr/local/bin/ghakustomize
          make kustomize
          mv ./bin/kustomize /usr/local/bin/kustomize
          kustomize version
        shell: bash

      - name: Build Operator
        run: |
          sudo -E make docker-build IMG=quay.io/ansible/galaxy-operator:main
          sudo -E docker images
        shell: bash

      - name: Prepare Object Storage
        run: |
          .ci/scripts/prepare-object-storage.sh
        shell: bash

      - name: Set imagePullPolicy to ifNotPresent
        run: |
          sed -i 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' config/manager/manager.yaml
        shell: bash

      - name: Deploy galaxy-operator to K8s
        run: sudo -E CI_TEST=galaxy ./up.sh
        shell: bash

      - name: Print Galaxy CR
        run: kubectl -n galaxy get galaxy example-galaxy -o yaml

      - name: Check and wait galaxy-operator deploy
        run: sudo -E time kubectl wait --for condition=Galaxy-Operator-Finished-Execution galaxy/example-galaxy --timeout=-1s
        shell: bash

      - name: KubeLinter
        run: .ci/scripts/kubelinter.sh
        shell: bash

      - name: Popeye
        run: |
          echo ::group::POPEYE
          sudo wget https://github.com/derailed/popeye/releases/download/v0.10.0/popeye_Linux_x86_64.tar.gz
          sudo tar -xvzf popeye_Linux_x86_64.tar.gz
          sudo mv popeye /usr/local/bin/
          sudo chmod +x /usr/local/bin/popeye
          echo ::endgroup::
          sudo popeye --kubeconfig ~/.kube/config || true

      - name: Test
        run: sudo -E .ci/scripts/galaxy_ng-tests.sh -m
        shell: bash

      - name: Backup & Restore
        run: CI_TEST=galaxy .ci/scripts/backup_and_restore.sh -m
        shell: bash
        env:
          PY_COLORS: '1'

      - name: Logs
        if: always()
        run: .github/workflows/scripts/show_logs.sh

      # - name: Debugging example (uncomment when needed)
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3

  validate-bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      # TODO: remove this step once the operator-sdk is available via the make operator-sdk target
      - name: Install Operator SDK
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/operator-framework/operator-sdk/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
          curl -o operator-sdk -L https://github.com/operator-framework/operator-sdk/releases/download/${VERSION}/operator-sdk_linux_amd64
          chmod +x operator-sdk
          sudo mv operator-sdk /usr/local/bin/

      - name: Validate OLM Bundle
        run: VERSION=0.0.0 make bundle
        shell: bash
